FROM python
RUN pip install flask
COPY ./static /home/myapp/static/
COPY ./templates /home/myapp/templates/
COPY ip_flask.py /home/myapp/
EXPOSE 5050
CMD python3 /home/myapp/ip_flask.py
FROM python
RUN pip install flask
COPY ./static /home/myapp/static/
COPY ./templates /home/myapp/templates/
COPY ip_flask.py /home/myapp/
EXPOSE 5050
CMD python3 /home/myapp/ip_flask.py
FROM python
RUN pip install flask
COPY ./static /home/myapp/static/
COPY ./templates /home/myapp/templates/
COPY ip_flask.py /home/myapp/
EXPOSE 5050
CMD python3 /home/myapp/ip_flask.py
FROM python
RUN pip install flask
COPY ./static /home/myapp/static/
COPY ./templates /home/myapp/templates/
COPY ip_flask.py /home/myapp/
EXPOSE 5050
CMD python3 /home/myapp/ip_flask.py
